spring:
  application:
    name: calangobets
  data:
    mongodb:
      uri: ${DB_URL}
  jpa:
    enabled: false


  cloud:
    compatibility-verifier:
      enabled: false

api:
  security:
    token:
      secret: ${JWT_SECRET:our-little-secret}

  main:
    allow-bean-definition-overriding: true
